apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-api-deployment
  labels:
    app: sms-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms-api
  template:
    metadata:
      labels:
        app: sms-api
    spec:
      containers:
      - name: sms-api
        image: peejayaccts/sms_api:1.1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3003