# sms deployment yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sms-deployment
  labels:
    app: sms
spec:
  replicas: 1 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
      - name: sms-api #1st container
        image: peejayaccts/sms-api:latest #Dockerhub image
        ports:
        - containerPort: 3003 #Exposes the port 8080 of the container
      - name:  sms-subscriber #2nd container
        image: peejayaccts/sms-subscriber:latest
        ports:
        - containerPort: 32463 
---
kind: Service
apiVersion: v1
metadata:
  name: sms-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: sms
  ports:
  - name: sms-api-port
    protocol: TCP
    port: 3003
  - name: sms-subscriber-port
    protocol: TCP
    port: 32463 