kind: Deployment
apiVersion: apps/v1
metadata:
  name: sms-api-deployment
  labels: 
    app: sms-api
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sms-api
  template:
    metadata:
      labels:
        app: sms-api
    spec:
      containers:
      - name: sms-api
        image: peejayaccts/sms-api:latest
        ports:
        - containerPort: 3003
        env:
          name: PORT
          value: "3003"
      - name: gateway-graphql
        image: peejayaccts/gateway-graphql:latest
        ports:
        - containerPort: 4001
        env:
          name: PORT
          value: "4001"

