kind: Service
apiVersion: v1
metadata:
  name: sms-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: sms
  ports:
  - name: sms-api-port
    protocol: TCP
    port: 3003 
  - name: sms-subscriber-port
    protocol: TCP
    port: 8082