apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sms_api 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sms_api 
        track: stable
    spec:
      containers:
        - name: sms_api 
          image: "peejayaccts/sms_api:v11.0.0"
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 81
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 81
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1