kind: Deployment
apiVersion: apps/v1
metadata:
  name: sms-deployment
  labels:
    app: sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms-pods
    spec:
      containers:
      - name: sms-api
        image: "{{ .Values.smsAPIImage.repository }}:{{ .Values.smsAPIImage.tag }}"
        imagePullPolicy:  IfNotPresent
        ports:
        - containerPort: 3003 
      - name: sms-subscriber 
        image: "{{ .Values.smsSubscriberImage.repository }}:{{ .Values.smsSubscriberImage.tag }}"
        imagePullPolicy:  IfNotPresent 
        ports:
        - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: sms-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: sms-pods
  ports:
  - name: sms-api-port
    protocol: TCP
    port: 3003 
  - name: sms-subscriber-port
    protocol: TCP
    port: 8082